export const languages = {
  "pt-br": {
    home: "Home",
    about: "Sobre",
    skills: "Habilidades",
    projects: "Projetos",
    contact: "Contatos",
    hero_greeting: "Olá, sou",
    hero_title: "Bruno Dias",
    hero_description:
      "Desenvolvedor Full Stack apaixonado por criar aplicações web modernas, responsivas e escaláveis. Especializado em React, Next.js e TypeScript.",
    github_btn: "GitHub",
    linkedin_btn: "LinkedIn",
    contact_btn: "Entrar em contato",
    contact_title: "Vamos conversar!",
    contact_description:
      "Tenho interesse em ouvir sobre seus projetos. Preencha o formulário abaixo.",
    form_name: "Nome",
    form_name_placeholder: "Seu nome",
    form_email: "E-mail",
    form_email_placeholder: "seu@email.com",
    form_message: "Mensagem",
    form_message_placeholder: "Sua mensagem aqui...",
    form_submit: "Enviar Mensagem",
    form_sending: "Enviando...",
    form_sent: "✓ Mensagem enviada!",
  },
  en: {
    home: "Home",
    about: "About",
    skills: "Skills",
    projects: "Projects",
    contact: "Contacts",
    hero_greeting: "Hi, I'm",
    hero_title: "Bruno Dias",
    hero_description:
      "Full Stack developer passionate about creating modern, responsive, and scalable web applications. Specialized in React, Next.js and TypeScript.",
    github_btn: "GitHub",
    linkedin_btn: "LinkedIn",
    contact_btn: "Get in Touch",
    contact_title: "Let's talk!",
    contact_description:
      "I'm interested in hearing about your projects. Fill out the form below.",
    form_name: "Name",
    form_name_placeholder: "Your name",
    form_email: "Email",
    form_email_placeholder: "your@email.com",
    form_message: "Message",
    form_message_placeholder: "Your message here...",
    form_submit: "Send Message",
    form_sending: "Sending...",
    form_sent: "✓ Message sent!",
  },
  es: {
    home: "Inicio",
    about: "Sobre",
    skills: "Habilidades",
    projects: "Proyectos",
    contact: "Contactos",
    hero_greeting: "Hola, soy",
    hero_title: "Bruno Dias",
    hero_description:
      "Desarrollador Full Stack apasionado por crear aplicaciones web modernas, responsivas y escalables. Especializado en React, Next.js y TypeScript.",
    github_btn: "GitHub",
    linkedin_btn: "LinkedIn",
    contact_btn: "Ponte en contacto",
    contact_title: "¡Hablemos!",
    contact_description:
      "Me interesa saber sobre tus proyectos. Completa el formulario a continuación.",
    form_name: "Nombre",
    form_name_placeholder: "Tu nombre",
    form_email: "Correo electrónico",
    form_email_placeholder: "tu@email.com",
    form_message: "Mensaje",
    form_message_placeholder: "Tu mensaje aquí...",
    form_submit: "Enviar Mensaje",
    form_sending: "Enviando...",
    form_sent: "✓ ¡Mensaje enviado!",
  },
};

export type Language = keyof typeof languages;
export type Translations = (typeof languages)["pt-br"];
